### ISSUE TITLE
[Feature request] Add support for a command line argument to turn modloader off

### ISSUE THREAD

**Issue by SinZ163** [risk-of-thunder/SeikoML#5]
This would make it easier to easily play with mods and vanilla at the same time as you can just have a shortcut to launch with the arguments to play rather than deal with making batch scripts or mod managers to deal with turning things on and off

**Comment by yoshisman8** [comment]
That is a feature we are figuring out how to set up, since right now the modloader is applied as a patch and thus can't really be turned 'off' However. If you know how to make a .bat script that allows you to 'uninstall' (swap the patched dll with the vanilla dll) the modloader and then run the game feel free to share it with us!

**Comment by Leeous** [comment]
Here's a [basic Python executable](https://drive.google.com/open?id=1fHmbZB-pk9oMJgLYAq7fqtQFnFuF2YaT) that'll switch the DLLs around for you. 
It goes in `Risk of Rain 2_Data\Managed\`.

**Comment by SinZ163** [comment]
It could still patch, but version number change and mod loading itself via the modloader is done at runtime right? Just not changing the version field would mean it's allowed to be in vanilla lobbies and can add a short circuit in ModLoader begin to abort and not load the other mods
